/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package softwareeng;

import java.sql.*;
import java.util.ResourceBundle;
import java.util.Scanner;

public class App {
    public static void main(String[] args) throws Exception {

        while (true) {
            String role = "";
            role = Auth.main();

            if (role.equals("acad")) {
                AcadOffice.main();
            } else if (role.equals("faculty")) {
                Faculty.main();
            } else if (role.equals("student")) {
                Student.main();
            } else {
                System.out.println("Logged out");
            }
        }
    }
}
